[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[functions]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/friends-leaderboard"
  status = 200
  to = "/.netlify/functions/friends-leaderboard"

[[redirects]]
  force = true
  from = "/api/ping"
  status = 200
  to = "/.netlify/functions/ping"

[[redirects]]
  force = true
  from = "/api/webhook"
  status = 200
  to = "/.netlify/functions/webhook"
